server:
  port: 80
  servlet:
    context-path: /diary
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: user01
    url: jdbc:mysql://mysqldb:3306/fisa?characterEncoding=UTF-8 
    username: user01
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true 
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp